# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'pennyway-client-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftFormat/CLI'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
# Pods for pennyway-client-iOS

end