# workflow 이름
name: test-CI

# workflow가 언제 실행될지에 대한 설명(When)
on:
  # main 브랜치에 pr을 올리는 경우(main 브랜치에서 분기한 브랜치도 실행된다.)
  pull_request:
    branches: 
      - 'dev'

# workflow가 어떻게 실행될지에 대한 설명(How)
jobs:
  build: # 빌드 및 테스트 작업 정의
    runs-on: macos-latest # macOS 환경에서 워크플로 실행 (iOS 프로젝트를 위해 macOS 필요)
    
    defaults:
      run:
        working-directory: ./pennyway-client-iOS # 작업 디렉토리를 fastlane이 포함된 iOS 프로젝트 폴더로 설정

    steps:
    - uses: actions/checkout@v2 # 리포지토리 코드를 현재 작업 디렉토리로 체크아웃

    - uses: ruby/setup-ruby@v1 # Ruby 환경 설정
      with:
        ruby-version: 2.7 # 프로젝트에서 사용할 Ruby 버전 명시
        
    - name: Create xcconfig files
      run: |
        echo "${{ secrets.TEST_CONFIG }}" > ./pennyway-client-iOS/Xcconfig/Test.xcconfig
        echo "${{ secrets.RELEASE_CONFIG }}" > ./pennyway-client-iOS/Xcconfig/Release.xcconfig
        echo "${{ secrets.DEBUG_CONFIG }}" > ./pennyway-client-iOS/Xcconfig/Debug.xcconfig
        echo "${{ secrets.SECRETS_CONFIG }}" > ./pennyway-client-iOS/Xcconfig/Secrets.xcconfig

    - name: Install Bundler # Ruby 의존성 관리 도구(Bundler) 설치
      run: gem install bundler -v 2.4.22

    - name: Install Fastlane # Fastlane 설치 (iOS CI/CD를 위한 도구)
      run: brew install fastlane

    - name: Verify Fastlane Installation # Fastlane이 제대로 설치되었는지 확인
      run: fastlane --version

    - name: Install dependencies # Gemfile에 정의된 Ruby 의존성 설치
      run: bundle _2.4.22_ install
      
    - name: Install Pod
      run: pod install --repo-update --clean-install

    - name: Run tests with Fastlane # Fastlane을 사용해 테스트 실행
      run: bundle exec fastlane tests
